
---
deployment:
      tasks:
        - export DEPLOYPATH=/home/apionetco/repositories/voip  # Add /<app_folder> if required
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        
