
---
deployment:
      tasks:
        - export DEPLOYPATH=/home/apionetco/public_html/api  # Add /<app_folder> if required
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        
